name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          for file in *.html; do
            echo "<url><loc>https://thanhbinhmta2707.github.io/binh/$file</loc></url>" >> sitemap.xml
          done

          echo '</urlset>' >> sitemap.xml

      - name: Commit sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "update sitemap" || echo "No changes"
          git push
